name: Generate EPG
on:
  workflow_dispatch: # Allows you to run it manually with a button
  schedule:
    - cron: '0 4 * * *' # Runs automatically every day at 4 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run Script
        run: python convert.py
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sports.xml
          git commit -m "Update EPG" || exit 0
          git push
